#!/bin/bash

window=$(xdotool getactivewindow)

set -- junk $(cat ~/.config/emoji | cut -d '|' -f 1 | dmenu -p emoji)

shift

if [ $# -eq 0 ]; then
    exit
fi

emoji=$(grep "^$(echo $@)|" ~/.config/emoji | cut -d '|' -f 2)

echo "$emoji" | xclip -selection clipboard

xdotool windowactivate $window
