#!/bin/bash

set -- junk $(cat ~/.config/emoji | cut -d '|' -f 1 | dmenu -p emoji)

shift

if [ $# -eq 0 ]; then
    exit
fi

grep "^$(echo $@)|" ~/.config/emoji | cut -d '|' -f 2 | xclip -selection clipboard

